# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [4]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10

In [5]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
print(a.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [13]:
np.info(np.add)
# np.add?
# numpy?

Object `numpy` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [16]:
b=np.zeros(10,dtype='int')
b[4]=1
print(b)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [21]:
c=np.random.randint(10,49,size=(3,3))
print(c)

[[17 12 25]
 [14 23 25]
 [26 36 48]]


#### 8.  Reverse a vector (first element becomes last)

In [26]:
d=np.array([1,2,3])
d=d[::-1]
print(d)

[3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
cc=np.random.randint(0,8,size=(3,3))
print(cc)

[[7 1 0]
 [2 7 4]
 [2 5 2]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [33]:
print(np.where(cc!=0))


(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 0, 1, 2, 0, 1, 2], dtype=int64))


#### 11. Create a 3x3 identity matrix

In [34]:
aaa=np.eye(3)
print(aaa)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [35]:
aq=np.random.randint(0,8,size=(3,3,3))
print(aq)

[[[5 2 6]
  [3 7 3]
  [6 3 4]]

 [[0 2 0]
  [2 1 0]
  [2 5 4]]

 [[2 4 2]
  [2 6 0]
  [7 5 3]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [39]:
aq=np.random.randint(0,8,size=(10,10))
print(aq)
print(np.min(aq))

print(np.max(aq))


[[3 0 2 7 3 2 4 4 0 5]
 [7 7 0 4 6 4 2 2 1 0]
 [7 5 4 4 4 2 3 4 3 4]
 [2 2 6 1 6 2 3 3 6 7]
 [2 7 0 1 4 0 3 1 0 1]
 [7 3 7 2 1 5 4 7 5 4]
 [3 3 0 5 1 0 7 3 4 0]
 [3 6 4 3 0 7 4 2 2 0]
 [5 0 1 2 5 4 3 6 4 7]
 [5 0 6 7 3 6 1 7 0 6]]
0
7


#### 14. Create a random vector of size 30 and find the mean value

In [40]:
aqq=np.random.randint(0,8,size=(30))
print(aqq)
print(np.mean(aqq))



[1 3 6 3 2 4 2 7 2 5 3 6 1 2 4 7 7 5 3 4 5 5 7 6 1 2 4 3 6 2]
3.933333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside

In [43]:
a=np.ones((5,5))
a[1:4,1:4]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [49]:
z=np.random.randint(1,8,size=(5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0 0 0 0 0 0 0]
 [0 4 2 3 4 7 0]
 [0 1 7 4 6 3 0]
 [0 1 2 4 3 1 0]
 [0 2 7 4 7 5 0]
 [0 3 5 4 3 7 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [47]:
a=np.zeros((8,8),dtype='int')
a[0::2,0::2]=1
a[1::2,1::2]=1

print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [67]:
r=np.random.randint(1,60,size=(6,7,8))
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
